service: dynamoDB-crud-api
provider:
  name: aws
  runtime: nodejs.14.x
  stage: dev
  region: ap-south-1
  environment: 
    DynamoDB_TABLE_NAME: ${self:custom.userTableName}
  
custom: 
  userTableName: usert-table-${self:provider.stage}

plugins:
  -serverless-iam-roles-per-function

functions:
  getUser:
    handler: api.getUser
    name: get-user
    memorySize: 128 # mb
    timeout: 5 # seconds
    events: 
      -http: 
        path: api/{userId}
        method: GET
    iamRoleStatements: 
      -Effect: "Allow"
      Action: 
        -"dynamodb.GetItem"
      Resource: !GetAtt UserTable.Arn
  createUser:
    handler: api.putUser
    name: create-user
    memorySize: 128 # mb
    timeout: 5 # seconds
    events: 
      -http: 
        path: api
        method: POST
    iamRoleStatements: 
      -Effect: "Allow"
      Action: 
        -"dynamodb.PutItem"
      Resource: !GetAtt UserTable.Arn      
  updateUser:
    handler: api.putUser
    name: update-user
    memorySize: 128 # mb
    timeout: 5 # seconds
    events: 
      -http: 
        path: api/{userId}
        method: PUT
    iamRoleStatements: 
      -Effect: "Allow"
      Action: 
        -"dynamodb.UpdateItem"
      Resource: !GetAtt UserTable.Arn
  deleteUser:
    handler: api.deleteUser
    name: delete-user
    memorySize: 128 # mb
    timeout: 5 # seconds
    events: 
      -http: 
        path: api
        method: DELETE
    iamRoleStatements: 
      -Effect: "Allow"
      Action: 
        -"dynamodb.DeleteItem"
      Resource: !GetAtt UserTable.Arn    

resources: 
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:custm.userTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
        - AttributeName: name
          AttributeType: S
        - AttributeName: username
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: avatar
          AttributeType: S
        - AttributeName: address
          AttributeType: M
        - AttributeName: phone
          AttributeType: S
        - AttributeName: website
          AttributeType: S
        - AttributeName: company_name
          AttributeType: S
        - AttributeName: catch_phrase
          AttributeType: S
        - AttributeName: street
          AttributeType: S
        - AttributeName: suite
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: zipcode
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
